# Generated by Django 4.2.24 on 2026-09-23 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_widen_employee_phone_64'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('late', 'Late'), ('out', 'Out')], max_length=10)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('expected_arrival', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('filed_by_self', models.BooleanField(default=True)),
                ('filed_by_name', models.CharField(blank=True, default='', max_length=120)),
                ('filed_at', models.DateTimeField()),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('excused', 'Excused'), ('void', 'Void')], default='requested', max_length=12)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status_changed_by', models.CharField(blank=True, default='', max_length=254)),
                ('status_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccdocs_attendance_notices', to='employee.employee')),
            ],
            options={
                'ordering': ['-filed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DayResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('status', models.CharField(choices=[('on_time', 'On time'), ('late', 'Late'), ('out', 'Out'), ('excused', 'Excused'), ('not_scored', 'Not scored')], max_length=12)),
                ('scheduled_start', models.TimeField(blank=True, null=True)),
                ('first_login_at', models.DateTimeField(blank=True, null=True)),
                ('minutes_late', models.IntegerField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('run_id', models.CharField(blank=True, default='', max_length=120)),
                ('excused_by', models.CharField(blank=True, default='', max_length=254)),
                ('excused_at', models.DateTimeField(blank=True, null=True)),
                ('excuse_reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccdocs_attendance_days', to='employee.employee')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccdocs_attendance.attendancenotice')),
            ],
            options={
                'ordering': ['-day', 'employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('late_email', 'Late email'), ('out_email', 'Out email'), ('digest', 'Digest email'), ('announce', 'Announcement'), ('slack_notin', 'Slack not-in post'), ('slack_close', 'Slack day summary'), ('slack_counts', 'Slack counts line'), ('slack_hold', 'Slack hold post')], max_length=20)),
                ('status', models.CharField(choices=[('attempting', 'Attempting'), ('sent', 'Sent'), ('failed', 'Failed')], default='attempting', max_length=12)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialer_user', models.CharField(blank=True, max_length=40, null=True)),
                ('webwork_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccdocs_attendance_links', to='employee.employee')),
            ],
            options={
                'ordering': ['employee_id', 'valid_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('rule_key', models.CharField(max_length=40)),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idem_key', models.CharField(max_length=120, unique=True)),
                ('source', models.CharField(choices=[('engine', 'Engine'), ('sarthak', 'Sarthak')], default='engine', max_length=10)),
                ('run_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_by', models.CharField(blank=True, default='', max_length=254)),
                ('void_reason', models.CharField(blank=True, default='', max_length=300)),
                ('day_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccdocs_attendance.dayresult')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ccdocs_attendance_points', to='employee.employee')),
            ],
            options={
                'ordering': ['-day', '-id'],
                'indexes': [models.Index(fields=['employee', 'day'], name='ccdocs_atte_employe_f0862f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dayresult',
            constraint=models.UniqueConstraint(fields=('employee', 'day'), name='ccdocs_att_one_result_per_day'),
        ),
        migrations.AddIndex(
            model_name='attendancenotice',
            index=models.Index(fields=['from_date', 'to_date'], name='ccdocs_atte_from_da_0b5fd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancenotice',
            constraint=models.CheckConstraint(check=models.Q(('to_date__gte', models.F('from_date'))), name='ccdocs_att_notice_dates_in_order'),
        ),
        migrations.AddConstraint(
            model_name='agentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True), ('dialer_user__isnull', False)), fields=('dialer_user',), name='ccdocs_att_one_open_holder_per_login'),
        ),
        migrations.AddConstraint(
            model_name='agentlink',
            constraint=models.CheckConstraint(check=models.Q(('dialer_user__isnull', False), ('webwork_email__isnull', False), _connector='OR'), name='ccdocs_att_link_has_a_login'),
        ),
    ]
