# Generated by Django 4.2.24 on 2026-09-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ccdocs_attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="kind",
            field=models.CharField(
                choices=[
                    ("late_email", "Late email"),
                    ("out_email", "Out email"),
                    ("digest", "Digest email"),
                    ("announce", "Announcement"),
                    ("slack_notin", "Slack not-in post"),
                    ("slack_close", "Slack day summary"),
                    ("slack_counts", "Slack counts line"),
                    ("slack_hold", "Slack hold post"),
                    ("pause_switch", "Pause switch message"),
                ],
                max_length=20,
            ),
        ),
    ]
